"""add social login fields

Revision ID: 5dc709d3b6d8
Revises: ec067bea7647
Create Date: 2026-07-30 16:30:27.758817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5dc709d3b6d8'
down_revision: Union[str, Sequence[str], None] = 'ec067bea7647'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('refresh_tokens')
    op.add_column('users', sa.Column('facebook_id', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('google_id', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('linkedin_id', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('instagram_id', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('twitter_id', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('profile_image', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('phone', sa.String(length=50), nullable=True))
    op.add_column(
    'users',
    sa.Column(
        'auth_provider',
        sa.String(length=50),
        nullable=False,
        server_default="email"
    )
)
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.create_index(op.f('ix_users_facebook_id'), 'users', ['facebook_id'], unique=True)
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)
    op.create_index(op.f('ix_users_instagram_id'), 'users', ['instagram_id'], unique=True)
    op.create_index(op.f('ix_users_linkedin_id'), 'users', ['linkedin_id'], unique=True)
    op.create_index(op.f('ix_users_twitter_id'), 'users', ['twitter_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_twitter_id'), table_name='users')
    op.drop_index(op.f('ix_users_linkedin_id'), table_name='users')
    op.drop_index(op.f('ix_users_instagram_id'), table_name='users')
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.drop_index(op.f('ix_users_facebook_id'), table_name='users')
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('users', 'auth_provider')
    op.drop_column('users', 'phone')
    op.drop_column('users', 'profile_image')
    op.drop_column('users', 'twitter_id')
    op.drop_column('users', 'instagram_id')
    op.drop_column('users', 'linkedin_id')
    op.drop_column('users', 'google_id')
    op.drop_column('users', 'facebook_id')
    op.create_table('refresh_tokens',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('token', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('is_revoked', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('refresh_tokens_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('refresh_tokens_pkey')),
    sa.UniqueConstraint('token', name=op.f('refresh_tokens_token_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
