"""add post_media table

Revision ID: 7bcde30082b1
Revises: 13ebf1000855
Create Date: 2026-07-15 16:09:33.470865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7bcde30082b1'
down_revision: Union[str, Sequence[str], None] = '13ebf1000855'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_post_media_id'), table_name='post_media')
    op.drop_constraint(op.f('post_media_post_id_fkey'), 'post_media', type_='foreignkey')
    op.drop_constraint(op.f('post_media_media_id_fkey'), 'post_media', type_='foreignkey')
    op.create_foreign_key(None, 'post_media', 'posts', ['post_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'post_media', 'media', ['media_id'], ['id'], ondelete='CASCADE')
    op.drop_column('post_media', 'id')
    op.drop_column('post_media', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post_media', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('post_media', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_constraint(None, 'post_media', type_='foreignkey')
    op.drop_constraint(None, 'post_media', type_='foreignkey')
    op.create_foreign_key(op.f('post_media_media_id_fkey'), 'post_media', 'media', ['media_id'], ['id'])
    op.create_foreign_key(op.f('post_media_post_id_fkey'), 'post_media', 'posts', ['post_id'], ['id'])
    op.create_index(op.f('ix_post_media_id'), 'post_media', ['id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('token', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('is_revoked', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('refresh_tokens_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('refresh_tokens_pkey')),
    sa.UniqueConstraint('token', name=op.f('refresh_tokens_token_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
